apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: production
    labels:
      app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tiagomadeiradock/tokio-frontend:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.1"
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        env:
          - name: NODE_ENV
            value: "production"
          - name: API_URL
            valueFrom:
             configMapKeyRef:
                name: frontend-configmap
                key: vite-api-url
          - name: VITE_OTEL_SERVICE_NAME
            valueFrom:
             configMapKeyRef:
                name: frontend-configmap
                key: otel-service-name
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            valueFrom:
             configMapKeyRef:
                name: frontend-configmap
                key: otel-exporter-endpoint

      imagePullSecrets:
      - name: regcred
       
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-internal-service
  namespace: production
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80