apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: dev-secure-backend-transport
  namespace: development
spec:
  # Overrides the Pod IP mismatch by forcing Traefik to validate against this domain
  serverName: development.backend.blog-posts.com.localhost
  rootCAsSecrets:
    - dev-backend-ca 