FROM python:3.12.3-slim

# 1. Create the user and group
RUN groupadd -r appuser && useradd -r -g appuser appuser

# 2. Create the app directory and set ownership as appuser
# This ensures SQLite can create journal files in the folder
RUN mkdir -p /home/appuser/app && chown -R appuser:appuser /home/appuser/app

# 3. Set the Working Directory
WORKDIR /home/appuser/app

# 4. Install dependencies as root (standard practice for speed/caching)
COPY requirements-prd.txt .
RUN python3 -m venv /home/appuser/app/.venv && \
    /home/appuser/app/.venv/bin/pip install --no-cache-dir --upgrade pip==26.0 && \
    /home/appuser/app/.venv/bin/pip install --no-cache-dir -r requirements-prd.txt

# 5. Switch to the non-root user
USER appuser

# 6. Copy the code into the WORKDIR (which is already owned by appuser)
COPY --chown=appuser:appuser ./app ./app

# 7. Use the venv explicitly in the CMD
ENV PATH="/home/appuser/app/.venv/bin:$PATH"
CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0"]