FROM node:22-alpine AS build

WORKDIR /app

ARG NODE_ENV=development

COPY package*.json ./

RUN if [ "$NODE_ENV" = "production" ]; then \
      npm ci --omit=dev; \
    else \
      npm ci; \
    fi

COPY src/ ./src
COPY public/ ./public
COPY index.html vite.config.ts tsconfig.json tsconfig.app.json tsconfig.node.json replace-env.sh ./

RUN npx vite build --mode ${NODE_ENV}

# Serve via Nginx
FROM nginx:stable-alpine
COPY default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

COPY replace-env.sh /docker-entrypoint.d/replace-env.sh

# Fix Windows line endings and make it executable
RUN sed -i 's/\r$//' /docker-entrypoint.d/replace-env.sh && \
    chmod +x /docker-entrypoint.d/replace-env.sh

EXPOSE 80