FROM node:22-alpine AS build

WORKDIR /app

ARG NODE_ENV=development

COPY package*.json ./

RUN if [ "$NODE_ENV" = "production" ]; then \
      npm ci --omit=dev; \
    else \
      npm ci; \
    fi

COPY . .

RUN npx vite build --mode ${NODE_ENV}

# Serve via Nginx
FROM nginx:stable-alpine
COPY default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]