sonar.organization=tiagomadeira
sonar.projectKey=TiagoMadeira_tokio_final

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=auth_service/app,post_service/app,rest_service/app,frontend/src,k8s-configs

sonar.tests=auth_service/tests,post_service/tests,rest_service/tests,frontend/tests

sonar.test.inclusions=**/*test*/**,**/*.spec.ts,**/*.test.ts,**/tests/**
sonar.cpd.exclusions=**/*test*/**,**/*.spec.ts,**/*.test.ts,**/tests/**