sonar.organization=tiagomadeira
sonar.projectKey=TiagoMadeira_tokio_final


sonar.sources=auth_service/app,post_service/app,rest_service/app,frontend/src,k8s-configs

sonar.exclusions=k8s-configs/**/*,**/tests/**,**/*test*/**,**/*.spec.ts,**/*.test.ts


sonar.tests=auth_service/tests,post_service/tests,rest_service/tests,frontend/tests


sonar.test.inclusions=auth_service/tests/**/*,post_service/tests/**/*,rest_service/tests/**/*,frontend/tests/**/*
sonar.cpd.exclusions=auth_service/tests/**/*,post_service/tests/**/*,rest_service/tests/**/*,frontend/tests/**/*



#######################################Coverage Exclusions#########################################################

sonar.coverage.exclusions=k8s-configs/**/*
#######################################Test Coverage Files#########################################################

# Python coverage files
sonar.python.coverage.reportPaths=auth_service/coverage.xml,post_service/coverage.xml,rest_service/coverage.xml

# Frontend JavaScript/TypeScript coverage file
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info