name: test_auth_service
description: Test auth service

inputs:
  jwt_secret:
    description: requirement file to be used
    required: false
  service_path:
    required: true
    description: path to the service being tested
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python  # Uses python version in .python-version file
      uses: actions/setup-python@v6

    - name: Set conditional env
      env:
        JWT_SECRET: ${{ inputs.jwt_secret }}
      shell: bash
      run: |
        if [ -n "$JWT_SECRET" ]; then
          echo "SECRET_KEY=$JWT_SECRET" >> $GITHUB_ENV
        fi

    - name: Setup isolated virtual environment and run tests
      env:
        SERVICE_PATH: ${{ inputs.service_path }}
      shell: bash
      run: |
        # Create and activate the venv inside the specific microservice folder
        python -m venv $SERVICE_PATH/.venv
        source $SERVICE_PATH/.venv/bin/activate
        
        pip install -r $SERVICE_PATH/requirements-stg.txt
        
        export PYTHONPATH=$SERVICE_PATH
        pytest $SERVICE_PATH/tests/ --cov=$SERVICE_PATH/app --cov-report=xml:$SERVICE_PATH/coverage.xml
        

    