apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-service-deployment
    namespace: development
    labels:
      app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: auth-service
        image: localhost:5000/tokio-auth-service:dev
        imagePullPolicy: Always
        workingDir: /home/appuser
        securityContext:
          runAsUser: 10001     # Matches the UID 10001 from your Dockerfile
          runAsGroup: 10001 
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

        volumeMounts:
          - name: app-write-space
            mountPath: /home/appuser/app/data

        resources:
          limits:
            memory: 512Mi
            cpu: "1"
            ephemeral-storage: "1Gi"
          requests:
            memory: 256Mi
            cpu: "0.1"
            ephemeral-storage: "256Mi"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8000
        env:
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: auth-service-configmap
                key: debug

          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            valueFrom:
              secretKeyRef:
                name: auth-service-secrets
                key: access_token_expire_minutes

          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-service-secrets
                key: secret-key

          - name: ALGORITHM
            valueFrom:
              secretKeyRef:
                name: auth-service-secrets
                key: algorithm
          
          - name: DATABASE_URL
            valueFrom:
             configMapKeyRef:
                name: auth-service-configmap
                key: database-url

          - name: OTEL_SERVICE_NAME
            valueFrom:
             configMapKeyRef:
                name: auth-service-configmap
                key: otel-service-name

          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            valueFrom:
             configMapKeyRef:
                name: auth-service-configmap
                key: otel-exporter-endpoint
          
          - name: OTEL_EXPORTER_OTLP_INSECURE 
            valueFrom:
             configMapKeyRef:
                name: auth-service-configmap
                key: otel-exporter-insecure

          - name: OTEL_METRICS_EXPORTER
            valueFrom:
             configMapKeyRef:
                name: auth-service-configmap
                key: otel-metrics-exporter

          - name: OTEL_LOGS_EXPORTER
            valueFrom:
             configMapKeyRef:
                name: auth-service-configmap
                key: otel-logs-exporter

      volumes:
        - name: app-write-space
          emptyDir: {}

              
---
apiVersion: v1
kind: Service
metadata:
  name: auth-internal-service
  namespace: development
spec:
  selector:
    app: auth-service
  type: ClusterIP
  ports:
    - port: 8888
      protocol: TCP
      targetPort: http