apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: development
    labels:
      app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10005  
        runAsGroup: 10005 
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: localhost:32000/tokio-frontend:dev
        imagePullPolicy: Always
        securityContext:
          runAsUser: 10005
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        resources:
          limits:
            memory: 512Mi
            cpu: "1"
            ephemeral-storage: "1Gi"
          requests:
            memory: 256Mi
            cpu: "0.1"
            ephemeral-storage: "500Mi"

        ports:
          - name: http
            protocol: TCP
            containerPort: 8080

        volumeMounts:
          - name: nginx-confd
            mountPath: /etc/nginx/conf.d
          - name: nginx-cache
            mountPath: /var/cache/nginx
          - name: nginx-pid
            mountPath: /var/run
          - name: nginx-tmp
            mountPath: /tmp

        env:
          - name: BACKEND_API_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: vite-backend-api-url

          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: otel-exporter-endpoint

          - name: VITE_OTEL_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: vite-otel-service-name


      volumes:
        - name: nginx-confd
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-pid
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
       
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-internal-service
  namespace: development
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080