FROM python:latest
COPY auth_service/requirements-dev.txt requirements-dev.txt
RUN python3 -m venv .venv
RUN . .venv/bin/activate
RUN pip install -r requirements-dev.txt
COPY . .
CMD ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0" ]