apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: development
data:
  vite-api-url: https://rest-internal-service.production.svc.cluster.local:80
  otel-service-name: production-frontend
  otel-exporter-endpoint: http://jaeger.observability.svc.cluster.local:4318