apiVersion: apps/v1
kind: Deployment
metadata:
    name: rest-service-deployment
    namespace: development
    labels:
      app: rest-service
spec:
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
      - name: rest-service
        image: tokio-rest-service:latest
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.1"
        volumeMounts:
          - name: certs
            mountPath: "/etc/tls"
            readOnly: true
        ports:
          - containerPort: 8000
        env:
          - name: DEBUG
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: debug
          - name: AUTH_SERVICE_URL
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: auth_service_url
          - name: POST_SERVICE_URL
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: post_service_url
          - name: OTEL_SERVICE_NAME
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: otel-service-name

          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: otel-exporter-endpoint
          
          - name: OTEL_EXPORTER_OTLP_INSECURE 
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: otel-exporter-insecure

          - name: OTEL_METRICS_EXPORTER
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: otel-metrics-exporter

          - name: OTEL_LOGS_EXPORTER
            valueFrom:
             configMapKeyRef:
                name: rest-service-configmap
                key: otel-logs-exporter
      volumes:
      - name: certs
        secret:
          secretName: backend-tls-secret
              
---
apiVersion: v1
kind: Service
metadata:
  name: rest-internal-service
  namespace: development
spec:
  selector:
    app: rest-service
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000