sonar.organization=tiagomadeira
sonar.projectKey=TiagoMadeira_tokio_final


sonar.sources=auth_service/app,post_service/app,rest_service/app,frontend/src,k8s-configs

sonar.exclusions=**/tests/**/*,**/*test*/**/*,**/*.spec.ts,**/*.test.ts, **/__pycache__/**, **/*.pyc, **/build-wrapper-dump.json, **/*.png, **/*.jpg, **/*.jpeg, **/*.gif, **/*.ico, **/*.svg

sonar.tests=auth_service/tests,post_service/tests,rest_service/tests,frontend/tests
sonar.test.inclusions=auth_service/tests/**/*,post_service/tests/**/*,rest_service/tests/**/*,frontend/tests/**/*
sonar.test.exclusions=**/__pycache__/**, **/*.pyc
sonar.cpd.exclusions=auth_service/tests/**/*,post_service/tests/**/*,rest_service/tests/**/*,frontend/tests/**/*

#######################################Coverage Exclusions#########################################################

sonar.coverage.exclusions=k8s-configs/**/*,frontend/src/main.tsx, frontend/src/tracing.ts, **/database/config.py, rest_service/app/main.py
#######################################Test Coverage Files#########################################################

# Python coverage files
sonar.python.coverage.reportPaths=auth_service/coverage.xml,post_service/coverage.xml,rest_service/coverage.xml

# Frontend JavaScript/TypeScript coverage file
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info