apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: jaeger
        image: docker.io/jaegertracing/all-in-one:latest
        securityContext:
          runAsUser: 10001        
          runAsGroup: 10001    
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        args: 
          - "--query.ui-config=/etc/jaeger-ui/jaeger-ui.json"
        volumeMounts:
        - name: ui-config-volume
          mountPath: /etc/jaeger-ui
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
            ephemeral-storage: "50Mi"
          limits:
            cpu: "20m"
            memory: "256Mi"   
            ephemeral-storage: "200Mi"
        env:
          - name: COLLECTOR_OTLP_ENABLED
            valueFrom:
              configMapKeyRef:
                name: jaeger-configmap
                key: collector_otlp_enabled             
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 6831
        - containerPort: 16686
        - containerPort: 14250

      volumes:
        - name: ui-config-volume
          configMap:
            name: jaeger-ui-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  name: jaeger
spec:
  selector:
    app: jaeger
  type: ClusterIP    
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: http
    port: 4318
    targetPort: 4318