apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-config
  namespace: observability
data:
  jaeger-ui.json: |
    {
      "themes": {
        "enabled": true,
        "default": "dark"
      }
    }