name: trivy_scan
description: Setup Environments and runs trivy_scan

inputs:
  service_path:
    description: path to the folder you want to be scanned
    required: true
  trivy_category:
    description: category
    required: true
  trivy_config_path:
    description: path to trivy config
    required: true
    
runs:
  using: "composite"
  steps:

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@v0.35.0
      env:
        # Forces Trivy to fetch online misconfig metadata from GitHub instead of Google
        TRIVY_CHECKS_BUNDLE_REPOSITORY: "ghcr.io/aquasecurity/trivy-checks:1"
      with:
        trivy-config: ${{ inputs.trivy_config_path }}
        scan-type: 'fs'
        scan-ref: ${{ inputs.service_path }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        cache-dir: '/tmp/trivy-cache-${{ inputs.service_path }}'
        exit-code: 0
        

    - name: Upload results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v4
      with:
        category: ${{ inputs.trivy_category }}
        sarif_file: 'trivy-results.sarif'
          