apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: development
data:
  vite-backend-api-url: https://rest-internal-service.development.svc.cluster.local:80
  vite-otel-service-name: development-frontend
  otel-exporter-endpoint: http://jaeger.observability.svc.cluster.local:4318