name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches:
      - master

jobs:
  dev:
    uses: ./.github/workflows/build-services.yaml
    secrets:
      dockerhub-access-token: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

  staging:
    runs-on: [self-hosted]
    needs: [dev]
    permissions:
      security-events: write
      contents: read
    defaults:
      run:
        shell: bash
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Set up Python  # Uses python version in .python-version file
        uses: actions/setup-python@v6

      - name: Pip audit Auth Service  # Uses python version in .python-version file
        run: |
          cd  blog_posts_app/auth_service
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install pip==${{vars.PIP_VERSION}}
          pip install pip-audit
          pip-audit -r requirements-prd.txt
      
      - name: Pip audit Post Service  # Uses python version in .python-version file
        run: |
          cd  blog_posts_app/post_service
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install pip==${{vars.PIP_VERSION}}
          pip install pip-audit
          pip-audit -r requirements-prd.txt
      
      - name: Pip audit Rest Service # Uses python version in .python-version file
        run: |
          cd  blog_posts_app/rest_service
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install pip==${{vars.PIP_VERSION}}
          pip install pip-audit
          pip-audit -r requirements-prd.txt

      - name: Run Trivy scan Auth Service
        run: |
          trivy fs --config blog_posts_app/trivy_conf/trivy.yaml --format table --exit-code 1 blog_posts_app/auth_service

      - name: Run Trivy scan Post Service
        run: | 
          trivy fs --config blog_posts_app/trivy_conf/trivy.yaml --format table --exit-code 1 blog_posts_app/post_service

      - name: Run Trivy scan Rest Service
        run: |
          trivy fs --config blog_posts_app/trivy_conf/trivy.yaml --format table --exit-code 1 blog_posts_app/rest_service

      - name: Run Trivy scan Frontend
        run: |
          trivy fs --config blog_posts_app/trivy_conf/trivy.yaml --format table --exit-code 1 blog_posts_app/frontend
        
      - name: Run Trivy scan K8s Configs
        run: |
          trivy fs --config blog_posts_app/trivy_conf/trivy.yaml --format table --exit-code 1 blog_posts_app/k8s-configs

      - name: Start and Configure MicroK8s
        run: |
          echo "Checking MicroK8s status..."
          if microk8s status 2>/dev/null | grep -q "microk8s is running"; then 
            echo "MicroK8s is already running."
          else 
            echo "MicroK8s is stopped. Starting MicroK8s..."
            microk8s start
            echo "Waiting for core services to initialize..."
            microk8s status --wait-ready >/dev/null 2>&1
            echo "MicroK8s is ready."
          fi
          
          echo "Enabling Ingress and DNS addons..."
          microk8s enable ingress
          microk8s enable dns
          
          echo "Enabling Hostpath Storage addon..."
          microk8s enable hostpath-storage
          
          echo "Enabling Built-in Registry addon..."
          microk8s enable registry
          
          echo "MicroK8s cluster is ready!"

      - name: Wait for Traefik Ingress
        run: |
          microk8s kubectl wait --namespace ingress \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/name=traefik \
          --timeout=120s
      
      - name: start obeservability server
        run: |
          echo "Checking for observability namespace..."
          if ! microk8s kubectl get namespace observability ; then
            microk8s kubectl create namespace observability
          fi
          echo "Applying configurations (idempotent)..."
          microk8s kubectl apply -f blog_posts_app/k8s-configs/observability/configmaps/jaeger-configmap.yaml
          microk8s kubectl apply -f blog_posts_app/k8s-configs/observability/configmaps/jaeger-ui-config.yaml
          microk8s kubectl apply -f blog_posts_app/k8s-configs/observability/manifests/jaeger-deployment.yaml
          microk8s kubectl apply -f blog_posts_app/k8s-configs/observability/ingress/jaeger-ingress.yaml
     
      - name: Wait for observability server to be up and running
        run: |
          microk8s kubectl wait --namespace observability \
          --for=condition=ready pod \
          --all \
          --timeout=240s

      - name: start staging server
        env:
          STAGING_BACKEND_TLS_CERT: ${{ secrets.STAGING_BACKEND_TLS_CERT }}
          STAGING_BACKEND_TLS_KEY: ${{ secrets.STAGING_BACKEND_TLS_KEY }}
          STAGING_FRONTEND_TLS_CERT: ${{ secrets.STAGING_FRONTEND_TLS_CERT }}
          STAGING_FRONTEND_TLS_KEY: ${{ secrets.STAGING_FRONTEND_TLS_KEY }}
          DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
        run: |
          if  microk8s kubectl get namespace staging ; then
            echo applying config files
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/frontend-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/auth-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/post-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/rest-service-configmap.yaml
            echo rollout deployments
            microk8s kubectl rollout restart deployment frontend-deployment -n staging
            microk8s kubectl rollout restart deployment auth-service-deployment -n staging
            microk8s kubectl rollout restart deployment post-service-deployment -n staging
            microk8s kubectl rollout restart deployment rest-service-deployment -n staging
          else
            # 1. Decode base64 secrets into temporary files
            echo "$STAGING_BACKEND_TLS_CERT" | base64 --decode > staging-backend-tls.crt
            echo "$STAGING_BACKEND_TLS_KEY" | base64 --decode > staging-backend-tls.key
            echo "$STAGING_BACKEND_TLS_CERT" | base64 --decode > staging-frontend-tls.crt
            echo "$STAGING_BACKEND_TLS_KEY" | base64 --decode > staging-frontend-tls.key

            echo create staging namespace
            microk8s kubectl create namespace staging
            echo appling pods secrets
            microk8s kubectl create secret docker-registry regcred --namespace staging --docker-server=https://index.docker.io/v1/ --docker-username=${{vars.DOCKER_USERNAME}} --docker-password=$DOCKERHUB_ACCESS_TOKEN --docker-email=${{vars.DOCKER_EMAIL}} > /dev/null 2>&1
            microk8s kubectl create secret tls backend-tls-secret --namespace staging --cert=staging-backend-tls.crt --key=staging-backend-tls.key
            microk8s kubectl create secret tls frontend-staging-posts-com-tls --namespace staging --cert=staging-frontend-tls.crt --key=staging-frontend-tls.key
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/secrets/auth-service-secrets.yaml
            echo applying config files
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/frontend-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/auth-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/post-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/configmaps/rest-service-configmap.yaml
            echo applying deployments
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/manifests/frontend-deployment.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/manifests/rest-service-deployment.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/manifests/post-service-deployment.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/manifests/auth-service-deployment.yaml
            echo applying ingresses
            microk8s kubectl apply -f blog_posts_app/k8s-configs/staging/ingress/frontend-posts-ingress.yaml

            # 3. Cleanup sensitive temporary files
            rm staging-backend-tls.crt staging-backend-tls.key staging-frontend-tls.crt staging-frontend-tls.key
          fi
      
      - name: Wait for pods in staging to be up and running
        run: |
          microk8s kubectl wait --namespace staging \
          --for=condition=ready pod \
          --all \
          --timeout=500s
      
      - name: Prepare rest service for integration testing
        run: |
         
          microk8s kubectl port-forward service/rest-internal-service 8000:80 -n staging &
          sleep 5 # Wait for the tunnel to initialize
      
      - name: Prepare frontend for e2e testing
        shell: bash
        run: |
          microk8s kubectl port-forward service/frontend-internal-service 3000:80 -n staging &
          sleep 5

      - name: auth service service unit testing
        env:
          JWT_SECRET: ${{ secrets.JWT_KEY }}
        shell: bash
        run: |
          echo "SECRET_KEY=$JWT_SECRET" >> $GITHUB_ENV
          python -m venv "$GITHUB_WORKSPACE/blog_posts_app/auth_service/.venv"
          source "$GITHUB_WORKSPACE/blog_posts_app/auth_service/.venv/bin/activate"
        
          pip install -r "$GITHUB_WORKSPACE/blog_posts_app/auth_service/requirements-stg.txt"
        
          export SECRET_KEY="$JWT_SECRET"
          export PYTHONPATH="$GITHUB_WORKSPACE/blog_posts_app/auth_service"

          pytest "$GITHUB_WORKSPACE/blog_posts_app/auth_service/tests/" \
            --cov="$GITHUB_WORKSPACE/blog_posts_app/auth_service/app" \
            --cov-report=xml:"$GITHUB_WORKSPACE/blog_posts_app/auth_service/coverage.xml"

      - name: post service unit testing
        shell: bash
        run: |
          python -m venv "$GITHUB_WORKSPACE/blog_posts_app/post_service/.venv"
          source "$GITHUB_WORKSPACE/blog_posts_app/post_service/.venv/bin/activate"
        
          pip install -r "$GITHUB_WORKSPACE/blog_posts_app/post_service/requirements-stg.txt"
        
          export PYTHONPATH="$GITHUB_WORKSPACE/blog_posts_app/post_service"
        
          pytest "$GITHUB_WORKSPACE/blog_posts_app/post_service/tests/" \
            --cov="$GITHUB_WORKSPACE/blog_posts_app/post_service/app" \
            --cov-report=xml:"$GITHUB_WORKSPACE/blog_posts_app/post_service/coverage.xml"

      - name: rest service unit and integration testing
        shell: bash
        run: |
          python -m venv "$GITHUB_WORKSPACE/blog_posts_app/rest_service/.venv"
          source "$GITHUB_WORKSPACE/blog_posts_app/rest_service/.venv/bin/activate"
        
          pip install -r "$GITHUB_WORKSPACE/blog_posts_app/rest_service/requirements-stg.txt"
        
          export PYTHONPATH="$GITHUB_WORKSPACE/blog_posts_app/rest_service"
        
          pytest "$GITHUB_WORKSPACE/blog_posts_app/rest_service/tests/" \
            --cov="$GITHUB_WORKSPACE/blog_posts_app/rest_service/app" \
            --cov-report=xml:"$GITHUB_WORKSPACE/blog_posts_app/rest_service/coverage.xml"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './blog_posts_app/frontend/package-lock.json'

      - name: frontend unit and integration testing and E2E
        shell: bash
        run: |
          cd  blog_posts_app/frontend
          npm ci
          npx playwright install chromium
          npm run test -- --coverage --watch=false
          npx playwright test   


      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          projectBaseDir: blog_posts_app

      - name: Clear Staging
        if: always()
        shell: bash
        run: |
          echo "Clearing staging..."
          minikube kubectl -- delete namespace staging --wait=true
        
          echo "Killing background staging port-forward processes..."
          kill $(pgrep -f "[p]ort-forward service/rest-internal-service 8000:80") 2>/dev/null || true
          kill $(pgrep -f "[p]ort-forward service/frontend-internal-service 3000:80") 2>/dev/null || true


  production:
    runs-on: [self-hosted]
    needs: [staging]
    defaults:
      run:
        # Use the built-in wsl shell handler
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start and Configure MicroK8s
        run: |
          echo "Checking MicroK8s status..."
          if microk8s status 2>/dev/null | grep -q "microk8s is running"; then 
            echo "MicroK8s is already running."
          else 
            echo "MicroK8s is stopped. Starting MicroK8s..."
            microk8s start
            echo "Waiting for core services to initialize..."
            microk8s status --wait-ready >/dev/null 2>&1
            echo "MicroK8s is ready."
          fi
          
          echo "Enabling Ingress and DNS addons..."
          microk8s enable ingress
          microk8s enable dns
          
          echo "Enabling Hostpath Storage addon..."
          microk8s enable hostpath-storage
          
          echo "Enabling Built-in Registry addon..."
          microk8s enable registry
          
          echo "MicroK8s cluster is ready!"

      - name: Wait for Traefik Ingress
        run: |
          microk8s kubectl wait --namespace ingress \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/name=traefik \
          --timeout=120s
      
      - name: start production server
        env: 
          DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
          PROD_BACK_TLS_CERT: ${{ secrets.TLS_CERT }}
          PROD_BACK_TLS_KEY: ${{ secrets.TLS_KEY }}
          PROD_FRONT_TLS_CERT: ${{ secrets.PROD_FRONT_TLS_CERT }}
          PROD_FRONT_TLS_KEY: ${{ secrets.PROD_FRONT_TLS_KEY }}
        run: |
          if  microk8s kubectl get namespace production; then
            echo applying config files
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/frontend-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/auth-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/post-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/rest-service-configmap.yaml
            echo rollout deployments
            microk8s kubectl rollout restart deployment frontend-deployment -n production
            microk8s kubectl rollout restart deployment auth-service-deployment -n production
            microk8s kubectl rollout restart deployment post-service-deployment -n production
            microk8s kubectl rollout restart deployment rest-service-deployment -n production
          else
            # 1. Decode base64 secrets into temporary files
            echo "$PROD_BACK_TLS_CERT" | base64 --decode --ignore-garbage > prod-backend-tls.crt
            echo "$PROD_BACK_TLS_KEY" | base64 --decode --ignore-garbage > prod-backend-tls.key
            echo "$PROD_FRONT_TLS_CERT" | base64 --decode --ignore-garbage > prod-frontend-tls.crt
            echo "$PROD_FRONT_TLS_KEY" | base64 --decode --ignore-garbage > prod-frontend-tls.key

            echo create production namespace
            microk8s kubectl create namespace production
            echo creating docker registry secret
            microk8s kubectl create secret docker-registry regcred --namespace production --docker-server=https://index.docker.io/v1/ --docker-username=${{vars.DOCKER_USERNAME}} --docker-password=$DOCKERHUB_ACCESS_TOKEN --docker-email=${{vars.DOCKER_EMAIL}} > /dev/null 2>&1
            echo appling pods secrets
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/secrets/auth-service-secrets.yaml
            microk8s kubectl create secret tls backend-tls-secret --namespace production --cert=prod-backend-tls.crt --key=prod-backend-tls.key
            microk8s kubectl create secret tls frontend-production-posts-com-tls --namespace production --cert=prod-frontend-tls.crt --key=prod-frontend-tls.key
            echo applying config files
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/frontend-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/auth-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/post-service-configmap.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/configmaps/rest-service-configmap.yaml
            echo applying deployments
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/manifests/frontend-deployment.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/manifests/rest-service-deployment.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/manifests/post-service-deployment.yaml
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/manifests/auth-service-deployment.yaml
            echo applying ingresses
            microk8s kubectl apply -f blog_posts_app/k8s-configs/production/ingress/frontend-posts-ingress.yaml
            # 3. Cleanup sensitive temporary files
            rm prod-backend-tls.crt prod-backend-tls.key prod-frontend-tls.crt prod-frontend-tls.key
          fi




    
