name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches:
      - master

jobs:
  # dev:
  #   uses: ./.github/workflows/build-services.yaml
  #   secrets:
  #     dockerhub-access-token: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

  staging:
    runs-on: [self-hosted-ubuntu]
    defaults:
      run:
        # Use the built-in wsl shell handler
        shell: bash
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Minikube status
        id: status_check
        continue-on-error: true 
        run: minikube status && echo "active=true" >> $GITHUB_OUTPUT || echo "active=false" >> $GITHUB_OUTPUT

      - name: start minikube
        if: steps.status_check.outputs.active == 'false'
        run: |
          cd k8s-configs
          make start_minikube

      - name: Wait for Ingress Controller
        run: |
          kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=120s
      
      - name: start obeservability server
        run: |
          cd k8s-configs
          if ! kubectl get namespace observability ; then
            make start_jaeger_server
          fi

      - name: start staging server
        run: |
          cd k8s-configs
          if  kubectl get namespace staging ; then
            make update_staging
          else
            make start_staging_environment docker_name=${{vars.DOCKER_USERNAME}} docker_password=${{secrets.DOCKERHUB_ACCESS_TOKEN}} docker_email=${{vars.DOCKER_EMAIL}}
          fi

      - name: Unit and integration testing
        uses: ./.github/worflows/test-services.yaml
        with: 
          jwt_secret: ${{secrets.JWT_KEY}}

  production:
    runs-on: [self-hosted-ubuntu]
    needs: [staging]
    defaults:
      run:
        # Use the built-in wsl shell handler
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Minikube status
        id: status_check
        continue-on-error: true 
        run: |
          if minikube status; then
            echo "active=true" >> $GITHUB_OUTPUT
          else
            echo "active=false" >> $GITHUB_OUTPUT
          fi

      - name: start minikube
        if: steps.status_check.outputs.active == 'false'
        run: |
          cd k8s-configs
          make minikube_start
      
      - name: start production server
        run: |
          cd k8s-configs
          if  kubectl get namespace production; then
            make update_production
          else
            make start_production_environment docker_name=${{vars.DOCKER_USERNAME}} docker_password=${{secrets.DOCKERHUB_ACCESS_TOKEN}} docker_email=${{DOCKER_EMAIL}}
          fi




    
