name: trivy-scan-services

on:
  workflow_dispatch:  
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

  
jobs:   
  
  trivy-scan-auth-service-dev:
     runs-on: this_pc_runner
     environment: ${{ inputs.environment }}
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivi Scan
        uses: ./.github/actions/trivy_scan
        with:
          trivy_config_path: ${{ vars.TRIVY_CONFIG_PATH }}
          service_path: "auth_service"

  trivy-scan-post-service-dev:
     runs-on: this_pc_runner
     environment: ${{ inputs.environment }}
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivi Scan
        uses: ./.github/actions/trivy_scan
        with:
          trivy_config_path: ${{ vars.TRIVY_CONFIG_PATH }}
          service_path: "post_service"
  
  trivy-scan-rest-service-dev:
     runs-on: this_pc_runner
     environment: ${{ inputs.environment }}
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivi Scan
        uses: ./.github/actions/trivy_scan
        with:
          trivy_config_path: ${{ vars.TRIVY_CONFIG_PATH }}
          service_path: "rest_service"